---
title: "Code Book"
output: html_document
author: José Cassio dos Santos Jr.
---
### Getting and Cleaning Data Project 
#### Experimental design and background

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details.

#### Raw data
We will be using a set of six raw data files, 3 sets for test data and 3 sets for training data.
Each correspondent file from both sets have identical layout.
Both sets of 3 files each are composed of 3 files That together identify the activity and the subject associated to the observations.

The description of these raw files follows bellow:

* activity_labels.txt
    
    + description: Links the class labels with their activity name. **Used only as a reference**. 
    
    + contents: activity label ID, activity name

* features.txt
    + description: List of all features measured and present into the X_test.txt and X_train.txt files. **Used only as a reference**.
    + contents: 
    
> test and train data sets

Both test and train datasets share the same file layout. The common description follows bellow:

* X_test.txt and X_train.txt
    + description: pre-processed sensor signals recorded from the test and train subjects
    + contents: 
Body acceleration mean time on direction X,
Body acceleration mean time on direction Y,
Body acceleration mean time on direction Z,
Body acceleration standard deviation time on direction X,
Body acceleration standard deviation time on direction Y,
Body acceleration standard deviation time on direction Z,
Body acceleration median absolute deviation time on direction X,
Body acceleration median absolute deviation time on direction Y,
Body acceleration median absolute deviation time on direction Z,
Body acceleration largest value time on direction X,
Body acceleration largest value time on direction Y,
Body acceleration largest value time on direction Z,
Body acceleration smallest value time on direction X,
Body acceleration smallest value time on direction Y,
Body acceleration smallest value time on direction Z,
Body acceleration signal magnitude area time,
Body acceleration energy measure time on direction X,
Body acceleration energy measure time on direction Y,
Body acceleration energy measure time on direction Z,
Body acceleration interquartile range time on direction X,
Body acceleration interquartile range time on direction Y,
Body acceleration interquartile range time on direction Z,
Body acceleration signal entropy time on direction X,
Body acceleration signal entropy time on direction Y,
Body acceleration signal entropy time on direction Z,
Body acceleration autorregresion coefficients with Burg order 1 time on direction X,
Body acceleration autorregresion coefficients with Burg order 2 time on direction X,
Body acceleration autorregresion coefficients with Burg order 3 time on direction X,
Body acceleration autorregresion coefficients with Burg order 4 time on direction X,
Body acceleration autorregresion coefficients with Burg order 1 time on direction Y,
Body acceleration autorregresion coefficients with Burg order 2 time on direction Y,
Body acceleration autorregresion coefficients with Burg order 3 time on direction Y,
Body acceleration autorregresion coefficients with Burg order 4 time on direction Y,
Body acceleration autorregresion coefficients with Burg order 1 time on direction Z,
Body acceleration autorregresion coefficients with Burg order 2 time on direction Z,
Body acceleration autorregresion coefficients with Burg order 3 time on direction Z,
Body acceleration autorregresion coefficients with Burg order 4 time on direction Z,
Body acceleration correlation coefficients between two signals time on direction X,
Body acceleration correlation coefficients between two signals time on direction Y,
Body acceleration correlation coefficients between two signals time on direction Z,
Gravity acceleration mean time on direction X,
Gravity acceleration mean time on direction Y,
Gravity acceleration mean time on direction Z,
Gravity acceleration standard deviation time on direction X,
Gravity acceleration standard deviation time on direction Y,
Gravity acceleration standard deviation time on direction Z,
Gravity acceleration median absolute deviation time on direction X,
Gravity acceleration median absolute deviation time on direction Y,
Gravity acceleration median absolute deviation time on direction Z,
Gravity acceleration largest value time on direction X,
Gravity acceleration largest value time on direction Y,
Gravity acceleration largest value time on direction Z,
Gravity acceleration smallest value time on direction X,
Gravity acceleration smallest value time on direction Y,
Gravity acceleration smallest value time on direction Z,
Gravity acceleration signal magnitude area time,
Gravity acceleration energy measure time on direction X,
Gravity acceleration energy measure time on direction Y,
Gravity acceleration energy measure time on direction Z,
Gravity acceleration interquartile range time on direction X,
Gravity acceleration interquartile range time on direction Y,
Gravity acceleration interquartile range time on direction Z,
Gravity acceleration signal entropy time on direction X,
Gravity acceleration signal entropy time on direction Y,
Gravity acceleration signal entropy time on direction Z,
Gravity acceleration autorregresion coefficients with Burg order 1 time on direction X,
Gravity acceleration autorregresion coefficients with Burg order 2 time on direction X,
Gravity acceleration autorregresion coefficients with Burg order 3 time on direction X,
Gravity acceleration autorregresion coefficients with Burg order 4 time on direction X,
Gravity acceleration autorregresion coefficients with Burg order 1 time on direction Y,
Gravity acceleration autorregresion coefficients with Burg order 2 time on direction Y,
Gravity acceleration autorregresion coefficients with Burg order 3 time on direction Y,
Gravity acceleration autorregresion coefficients with Burg order 4 time on direction Y,
Gravity acceleration autorregresion coefficients with Burg order 1 time on direction Z,
Gravity acceleration autorregresion coefficients with Burg order 2 time on direction Z,
Gravity acceleration autorregresion coefficients with Burg order 3 time on direction Z,
Gravity acceleration autorregresion coefficients with Burg order 4 time on direction Z,
Gravity acceleration correlation coefficients between two signals time on direction X,
Gravity acceleration correlation coefficients between two signals time on direction Y,
Gravity acceleration correlation coefficients between two signals time on direction Z,
Body acceleration jerk mean time on direction X,
Body acceleration jerk mean time on direction Y,
Body acceleration jerk mean time on direction Z,
Body acceleration jerk standard deviation time on direction X,
Body acceleration jerk standard deviation time on direction Y,
Body acceleration jerk standard deviation time on direction Z,
Body acceleration jerk median absolute deviation time on direction X,
Body acceleration jerk median absolute deviation time on direction Y,
Body acceleration jerk median absolute deviation time on direction Z,
Body acceleration jerk largest value time on direction X,
Body acceleration jerk largest value time on direction Y,
Body acceleration jerk largest value time on direction Z,
Body acceleration jerk smallest value time on direction X,
Body acceleration jerk smallest value time on direction Y,
Body acceleration jerk smallest value time on direction Z,
Body acceleration jerk signal magnitude area time,
Body acceleration jerk energy measure time on direction X
Body acceleration jerk energy measure time on direction Y
Body acceleration jerk energy measure time on direction Z
Body acceleration jerk interquartile range time on direction X,
Body acceleration jerk interquartile range time on direction Y,
Body acceleration jerk interquartile range time on direction Z,
Body acceleration jerk signal entropy time on direction X,
Body acceleration jerk signal entropy time on direction Y,
Body acceleration jerk signal entropy time on direction Z,
Body acceleration jerk autorregresion coefficients with Burg order 1 time on direction X,
Body acceleration jerk autorregresion coefficients with Burg order 2 time on direction X,
Body acceleration jerk autorregresion coefficients with Burg order 3 time on direction X,
Body acceleration jerk autorregresion coefficients with Burg order 4 time on direction X,
Body acceleration jerk autorregresion coefficients with Burg order 1 time on direction Y,
Body acceleration jerk autorregresion coefficients with Burg order 2 time on direction Y,
Body acceleration jerk autorregresion coefficients with Burg order 3 time on direction Y,
Body acceleration jerk autorregresion coefficients with Burg order 4 time on direction Y,
Body acceleration jerk autorregresion coefficients with Burg order 1 time on direction Z,
Body acceleration jerk autorregresion coefficients with Burg order 2 time on direction Z,
Body acceleration jerk autorregresion coefficients with Burg order 3 time on direction Z,
Body acceleration jerk autorregresion coefficients with Burg order 4 time on direction Z,
Body acceleration jerk correlation coefficients between two signals time on direction X,
Body acceleration jerk correlation coefficients between two signals time on direction Y,
Body acceleration jerk correlation coefficients between two signals time on direction Z,
Body gyroscopic mean time on direction X,
Body gyroscopic mean time on direction Y,
Body gyroscopic mean time on direction Z,
Body gyroscopic standard deviation time on direction X,
Body gyroscopic standard deviation time on direction Y,
Body gyroscopic standard deviation time on direction Z,
Body gyroscopic median absolute deviation time on direction X,
Body gyroscopic median absolute deviation time on direction Y,
Body gyroscopic median absolute deviation time on direction Z,
Body gyroscopic largest value time on direction X,
Body gyroscopic largest value time on direction Y,
Body gyroscopic largest value time on direction Z,
Body gyroscopic smallest value time on direction X,
Body gyroscopic smallest value time on direction Y,
Body gyroscopic smallest value time on direction Z,
Body gyroscopic signal magnitude area time,
Body gyroscopic energy measure time on direction X,
Body gyroscopic energy measure time on direction Y,
Body gyroscopic energy measure time on direction Z,
Body gyroscopic interquartile range time on direction X,
Body gyroscopic interquartile range time on direction Y,
Body gyroscopic interquartile range time on direction Z,
Body gyroscopic signal entropy time on direction X,
Body gyroscopic signal entropy time on direction Y,
Body gyroscopic signal entropy time on direction Z,
Body gyroscopic autorregresion coefficients with Burg order 1 time on direction X,
Body gyroscopic autorregresion coefficients with Burg order 2 time on direction X,
Body gyroscopic autorregresion coefficients with Burg order 3 time on direction X,
Body gyroscopic autorregresion coefficients with Burg order 4 time on direction X,
Body gyroscopic autorregresion coefficients with Burg order 1 time on direction Y,
Body gyroscopic autorregresion coefficients with Burg order 2 time on direction Y,
Body gyroscopic autorregresion coefficients with Burg order 3 time on direction Y,
Body gyroscopic autorregresion coefficients with Burg order 4 time on direction Y,
Body gyroscopic autorregresion coefficients with Burg order 1 time on direction Z,
Body gyroscopic autorregresion coefficients with Burg order 2 time on direction Z,
Body gyroscopic autorregresion coefficients with Burg order 3 time on direction Z,
Body gyroscopic autorregresion coefficients with Burg order 4 time on direction Z,
Body gyroscopic correlation coefficients between two signals time on direction X,
Body gyroscopic correlation coefficients between two signals time on direction Y,
Body gyroscopic correlation coefficients between two signals time on direction Z,
Body gyroscopic jerk mean time on direction X,
Body gyroscopic jerk mean time on direction Y,
Body gyroscopic jerk mean time on direction Z,
Body gyroscopic jerk standard deviation time on direction X,
Body gyroscopic jerk standard deviation time on direction Y,
Body gyroscopic jerk standard deviation time on direction Z,
Body gyroscopic jerk median absolute deviation time on direction X,
Body gyroscopic jerk median absolute deviation time on direction Y,
Body gyroscopic jerk median absolute deviation time on direction Z,
Body gyroscopic jerk largest value time on direction X,
Body gyroscopic jerk largest value time on direction Y,
Body gyroscopic jerk largest value time on direction Z,
Body gyroscopic jerk smallest value time on direction X,
Body gyroscopic jerk smallest value time on direction Y,
Body gyroscopic jerk smallest value time on direction Z,
Body gyroscopic jerk signal magnitude area time,
Body gyroscopic jerk energy measure time on direction X,
Body gyroscopic jerk energy measure time on direction Y,
Body gyroscopic jerk energy measure time on direction Z,
Body gyroscopic jerk interquartile range time on direction X,
Body gyroscopic jerk interquartile range time on direction Y,
Body gyroscopic jerk interquartile range time on direction Z,
Body gyroscopic jerk signal entropy time on direction X,
Body gyroscopic jerk signal entropy time on direction Y,
Body gyroscopic jerk signal entropy time on direction Z,
Body gyroscopic jerk autorregresion coefficients with Burg order 1 time on direction X,
Body gyroscopic jerk autorregresion coefficients with Burg order 2 time on direction X,
Body gyroscopic jerk autorregresion coefficients with Burg order 3 time on direction X,
Body gyroscopic jerk autorregresion coefficients with Burg order 4 time on direction X,
Body gyroscopic jerk autorregresion coefficients with Burg order 1 time on direction Y,
Body gyroscopic jerk autorregresion coefficients with Burg order 2 time on direction Y,
Body gyroscopic jerk autorregresion coefficients with Burg order 3 time on direction Y,
Body gyroscopic jerk autorregresion coefficients with Burg order 4 time on direction Y,
Body gyroscopic jerk autorregresion coefficients with Burg order 1 time on direction Z,
Body gyroscopic jerk autorregresion coefficients with Burg order 2 time on direction Z,
Body gyroscopic jerk autorregresion coefficients with Burg order 3 time on direction Z,
Body gyroscopic jerk autorregresion coefficients with Burg order 4 time on direction Z,
Body gyroscopic jerk correlation coefficients between two signals time on direction X,
Body gyroscopic jerk correlation coefficients between two signals time on direction Y,
Body gyroscopic jerk correlation coefficients between two signals time on direction Z,
Body acceleration mean time magnitude,
Body acceleration standard deviation time magnitude,
Body acceleration median absolute deviation time magnitude,
Body acceleration largest value time magnitude,
Body acceleration smallest value time magnitude,
Body gyroscopic signal magnitude area magnitude,
Body acceleration energy measure time magnitude,
Body acceleration interquartile range time magnitude,
Body acceleration signal entropy time magnitude,
Body acceleration autorregresion coefficients with Burg order 1 time magnitude,
Body acceleration autorregresion coefficients with Burg order 2 time magnitude,
Body acceleration autorregresion coefficients with Burg order 3 time magnitude,
Body acceleration autorregresion coefficients with Burg order 4 time magnitude,
Gravity acceleration mean time magnitude,
Gravity acceleration standard deviation time magnitude,
Gravity acceleration median absolute deviation time magnitude,
Gravity acceleration largest value time magnitude,
Gravity acceleration smallest value time magnitude,
Gravity gyroscopic signal magnitude area magnitude,
Gravity acceleration energy measure time magnitude,
Gravity acceleration interquartile range time magnitude,
Gravity acceleration signal entropy time magnitude,
Gravity acceleration autorregresion coefficients with Burg order 1 time magnitude,
Gravity acceleration autorregresion coefficients with Burg order 2 time magnitude,
Gravity acceleration autorregresion coefficients with Burg order 3 time magnitude,
Gravity acceleration autorregresion coefficients with Burg order 4 time magnitude,
Body acceleration jerk mean time magnitude,
Body acceleration jerk standard deviation time magnitude,
Body acceleration jerk median absolute deviation time magnitude,
Body acceleration jerk largest value time magnitude,
Body acceleration jerk smallest value time magnitude,
Body acceleration jerk signal magnitude area magnitude,
Body acceleration jerk energy measure time magnitude,
Body acceleration jerk interquartile range time magnitude,
Body acceleration jerk signal entropy time magnitude,
Body acceleration jerk autorregresion coefficients with Burg order 1 time magnitude,
Body acceleration jerk autorregresion coefficients with Burg order 2 time magnitude,
Body acceleration jerk autorregresion coefficients with Burg order 3 time magnitude,
Body acceleration jerk autorregresion coefficients with Burg order 4 time magnitude,
Body gyroscopic mean time magnitude,
Body gyroscopic standard deviation time magnitude,
Body gyroscopic median absolute deviation time magnitude,
Body gyroscopic largest value time magnitude,
Body gyroscopic smallest value time magnitude,
Body gyroscopic signal magnitude area magnitude,
Body gyroscopic energy measure time magnitude,
Body gyroscopic interquartile range time magnitude,
Body gyroscopic signal entropy time magnitude,
Body gyroscopic autorregresion coefficients with Burg order 1 time magnitude,
Body gyroscopic autorregresion coefficients with Burg order 2 time magnitude,
Body gyroscopic autorregresion coefficients with Burg order 3 time magnitude,
Body gyroscopic autorregresion coefficients with Burg order 4 time magnitude,
Body gyroscopic jerk mean time magnitude,
Body gyroscopic jerk standard deviation time magnitude,
Body gyroscopic jerk median absolute deviation time magnitude,
Body gyroscopic jerk largest value time magnitude,
Body gyroscopic jerk smallest value time magnitude,
Body gyroscopic jerk signal magnitude area magnitude,
Body gyroscopic jerk energy measure time magnitude,
Body gyroscopic jerk interquartile range time magnitude,
Body gyroscopic jerk signal entropy time magnitude,
Body gyroscopic jerk autorregresion coefficients with Burg order 1 time magnitude,
Body gyroscopic jerk autorregresion coefficients with Burg order 2 time magnitude,
Body gyroscopic jerk autorregresion coefficients with Burg order 3 time magnitude,
Body gyroscopic jerk autorregresion coefficients with Burg order 4 time magnitude,
Body acceleration mean FFT on direction X,
Body acceleration mean FFT on direction Y,
Body acceleration mean FFT on direction Z,
Body acceleration standard deviation FFT on direction X,
Body acceleration standard deviation FFT on direction Y,
Body acceleration standard deviation FFT on direction Z,
Body acceleration median absolute deviation FFT on direction X,
Body acceleration median absolute deviation FFT on direction Y,
Body acceleration median absolute deviation FFT on direction Z,
Body acceleration largest value FFT on direction X,
Body acceleration largest value FFT on direction Y,
Body acceleration largest value FFT on direction Z,
Body acceleration smallest value FFT on direction X,
Body acceleration smallest value FFT on direction Y,
Body acceleration smallest value FFT on direction Z,
Body acceleration signal magnitude area FFT,
Body acceleration energy measure FFT on direction X,
Body acceleration energy measure FFT on direction Y,
Body acceleration energy measure FFT on direction Z,
Body acceleration interquartile range FFT on direction X,
Body acceleration interquartile range FFT on direction Y,
Body acceleration interquartile range FFT on direction Z,
Body acceleration signal entropy FFT on direction X,
Body acceleration signal entropy FFT on direction Y,
Body acceleration signal entropy FFT on direction Z,
Body acceleration index of the frequency component with largest magnitude FFT on direction X,
Body acceleration index of the frequency component with largest magnitude FFT on direction Y,
Body acceleration index of the frequency component with largest magnitude FFT on direction Z,
Body acceleration weighted average of the frequency components to obtain a mean frequency FFT on direction X,
Body acceleration weighted average of the frequency components to obtain a mean frequency FFT on direction Y,
Body acceleration weighted average of the frequency components to obtain a mean frequency FFT on direction Z,
Body acceleration skewness of the frequency domain signal FFT on direction X,
Body acceleration kurtosis of the frequency domain signal FFT on direction X,
Body acceleration skewness of the frequency domain signal FFT on direction Y,
Body acceleration kurtosis of the frequency domain signal FFT on direction Y,
Body acceleration skewness of the frequency domain signal FFT on direction Z,
Body acceleration kurtosis of the frequency domain signal FFT on direction Z,
Body acceleration Energy of a frequency interval within the 64 bins of the FFT window 1-8,
Body acceleration energy of a frequency interval within the 64 bins of the FFT window 9-16,
Body acceleration energy of a frequency interval within the 64 bins FFT window 17-24,
Body acceleration energy of a frequency interval within the 64 bins FFT window 25-32,
Body acceleration energy of a frequency interval within the 64 bins FFT window 33-40,
Body acceleration energy of a frequency interval within the 64 bins FFT window 41-48,
Body acceleration energy of a frequency interval within the 64 bins FFT window 49-56,
Body acceleration energy of a frequency interval within the 64 bins FFT window 57-64,
Body acceleration energy of a frequency interval within the 64 bins FFT window 1-16,
Body acceleration energy of a frequency interval within the 64 bins FFT window 17-32,
Body acceleration energy of a frequency interval within the 64 bins FFT window 33-48,
Body acceleration energy of a frequency interval within the 64 bins FFT window 49,64-
Body acceleration energy of a frequency interval within the 64 bins FFT window 1,24-
Body acceleration energy of a frequency interval within the 64 bins FFT window 25,48-
Body acceleration energy of a frequency interval within the 64 bins FFT window 1,8-
Body acceleration energy of a frequency interval within the 64 bins FFT window 9,16-
Body acceleration energy of a frequency interval within the 64 bins FFT window 17,24-
Body acceleration energy of a frequency interval within the 64 bins FFT window 25,32-
Body acceleration energy of a frequency interval within the 64 bins FFT window 33-40,
Body acceleration energy of a frequency interval within the 64 bins FFT window 41-48,
Body acceleration energy of a frequency interval within the 64 bins FFT window 49-56,
Body acceleration energy of a frequency interval within the 64 bins FFT window 57-64-
Body acceleration energy of a frequency interval within the 64 bins FFT window 1,16-
Body acceleration energy of a frequency interval within the 64 bins FFT window 17,32-
Body acceleration energy of a frequency interval within the 64 bins FFT window 33,48-
Body acceleration energy of a frequency interval within the 64 bins FFT window 49-64,
Body acceleration energy of a frequency interval within the 64 bins FFT window 1-24,
Body acceleration energy of a frequency interval within the 64 bins FFT window 25-48,
Body acceleration energy of a frequency interval within the 64 bins FFT window 1-8,
Body acceleration energy of a frequency interval within the 64 bins FFT window 9-16,
Body acceleration energy of a frequency interval within the 64 bins FFT window 17-24,
Body acceleration energy of a frequency interval within the 64 bins FFT window 25-32,
Body acceleration energy of a frequency interval within the 64 bins FFT window 33-40,
Body acceleration energy of a frequency interval within the 64 bins FFT window 41-48,
Body acceleration energy of a frequency interval within the 64 bins FFT window 49-56,
Body acceleration energy of a frequency interval within the 64 bins FFT window 57-64,
Body acceleration energy of a frequency interval within the 64 bins FFT window 1-16,
Body acceleration energy of a frequency interval within the 64 bins FFT window 17-32,
Body acceleration energy of a frequency interval within the 64 bins FFT window 33-48,
Body acceleration energy of a frequency interval within the 64 bins FFT window 49-64,
Body acceleration energy of a frequency interval within the 64 bins FFT window 1-24,
Body acceleration energy of a frequency interval within the 64 bins FFT window 25-48,
Body acceleration jerk mean FFT on direction X,
Body acceleration jerk mean FFT on direction Y,
Body acceleration jerk mean FFT on direction Z,
Body acceleration jerk standard deviation FFT on direction X,
Body acceleration jerk standard deviation FFT on direction Y,
Body acceleration jerk standard deviation FFT on direction Z,
Body acceleration jerk median absolute deviation FFT on direction X,
Body acceleration jerk median absolute deviation FFT on direction Y,
Body acceleration jerk median absolute deviation FFT on direction Z,
Body acceleration jerk largest value FFT on direction X,
Body acceleration jerk largest value FFT on direction Y,
Body acceleration jerk largest value FFT on direction Z,
Body acceleration jerk smallest value FFT on direction X,
Body acceleration jerk smallest value FFT on direction Y,
Body acceleration jerk smallest value FFT on direction Z,
Body acceleration jerk signal magnitude area FFT,
Body acceleration jerk energy measure FFT on direction X,
Body acceleration jerk energy measure FFT on direction Y,
Body acceleration jerk energy measure FFT on direction Z,
Body acceleration jerk interquartile range FFT on direction X,
Body acceleration jerk interquartile range FFT on direction Y,
Body acceleration jerk interquartile range FFT on direction Z,
Body acceleration jerk signal entropy FFT on direction X,
Body acceleration jerk signal entropy FFT on direction Y,
Body acceleration jerk signal entropy FFT on direction Z,
Body acceleration jerk index of the frequency component with largest magnitude FFT on direction X,
Body acceleration jerk index of the frequency component with largest magnitude FFT on direction Y,
Body acceleration jerk index of the frequency component with largest magnitude FFT on direction Z,
Body acceleration jerk weighted average of the frequency components to obtain a mean frequency FFT on direction X,
Body acceleration jerk weighted average of the frequency components to obtain a mean frequency FFT on direction Y,
Body acceleration jerk weighted average of the frequency components to obtain a mean frequency FFT on direction Z,
Body acceleration jerk skewness of the frequency domain signal FFT on direction X,
Body acceleration jerk kurtosis of the frequency domain signal FFT on direction X,
Body acceleration jerk skewness of the frequency domain signal FFT on direction Y,
Body acceleration jerk kurtosis of the frequency domain signal FFT on direction Y,
Body acceleration jerk skewness of the frequency domain signal FFT on direction Z,
Body acceleration jerk kurtosis of the frequency domain signal FFT on direction Z,
Body acceleration jerk Energy of a frequency interval within the 64 bins of the FFT window 1-8,
Body acceleration jerk energy of a frequency interval within the 64 bins of the FFT window 9-16,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 17-24,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 25-32,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 33-40,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 41-48,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 49-56,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 57-64,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 1-16,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 17-32,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 33-48,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 49-64,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 1-24,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 25-48,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 1-8,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 9-16,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 17-24,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 25-32,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 33-40,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 41-48,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 49-56,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 57-64,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 1-16,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 17-32,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 33-48,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 49-64,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 1-24,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 25-48,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 1-8,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 9-16,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 17-24,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 25-32,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 33-40,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 41-48,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 49-56,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 57-64,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 1-16,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 17-32,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 33-48,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 49-64,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 1-24,
Body acceleration jerk energy of a frequency interval within the 64 bins FFT window 25-48,
Body gyroscopic mean FFT on direction X,
Body gyroscopic mean FFT on direction Y,
Body gyroscopic mean FFT on direction Z,
Body gyroscopic standard deviation FFT on direction X,
Body gyroscopic standard deviation FFT on direction Y,
Body gyroscopic standard deviation FFT on direction Z,
Body gyroscopic median absolute deviation FFT on direction X,
Body gyroscopic median absolute deviation FFT on direction Y,
Body gyroscopic median absolute deviation FFT on direction Z,
Body gyroscopic largest value FFT on direction X,
Body gyroscopic largest value FFT on direction Y,
Body gyroscopic largest value FFT on direction Z,
Body gyroscopic smallest value FFT on direction X,
Body gyroscopic smallest value FFT on direction Y,
Body gyroscopic smallest value FFT on direction Z,
Body gyroscopic signal magnitude area FFT,
Body gyroscopic energy measure FFT on direction X,
Body gyroscopic energy measure FFT on direction Y,
Body gyroscopic energy measure FFT on direction Z,
Body gyroscopic interquartile range FFT on direction X,
Body gyroscopic interquartile range FFT on direction Y,
Body gyroscopic interquartile range FFT on direction Z,
Body gyroscopic signal entropy FFT on direction X,
Body gyroscopic signal entropy FFT on direction Y,
Body gyroscopic signal entropy FFT on direction Z,
Body gyroscopic index of the frequency component with largest magnitude FFT on direction X,
Body gyroscopic index of the frequency component with largest magnitude FFT on direction Y,
Body gyroscopic index of the frequency component with largest magnitude FFT on direction Z,
Body gyroscopic weighted average of the frequency components to obtain a mean frequency FFT on direction X,
Body gyroscopic weighted average of the frequency components to obtain a mean frequency FFT on direction Y,
Body gyroscopic weighted average of the frequency components to obtain a mean frequency FFT on direction Z,
Body gyroscopic skewness of the frequency domain signal FFT on direction X,
Body gyroscopic kurtosis of the frequency domain signal FFT on direction X,
Body gyroscopic skewness of the frequency domain signal FFT on direction Y,
Body gyroscopic kurtosis of the frequency domain signal FFT on direction Y,
Body gyroscopic skewness of the frequency domain signal FFT on direction Z,
Body gyroscopic kurtosis of the frequency domain signal FFT on direction Z,
Body gyroscopic Energy of a frequency interval within the 64 bins of the FFT window 1-8,
Body gyroscopic energy of a frequency interval within the 64 bins of the FFT window 9-16,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 17-24,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 25-32,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 33-40,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 41-48,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 49-56,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 57-64,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 1-16,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 17-32,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 33-48,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 49-64,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 1-24,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 25-48,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 1-8,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 9-16,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 17-24,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 25-32,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 33-40,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 41-48,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 49-56,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 57-64,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 1-16,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 17-32,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 33-48,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 49-64,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 1-24,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 25-48,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 1-8,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 9-16,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 17-24,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 25-32,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 33-40,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 41-48,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 49-56,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 57-64,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 1-16,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 17-32,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 33-48,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 49-64,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 1-24,
Body gyroscopic energy of a frequency interval within the 64 bins FFT window 25-48,
Body acceleration mean FFT magnitude,
Body acceleration standard deviation FFT magnitude,
Body acceleration median absolute deviation FFT magnitude,
Body acceleration largest value FFT magnitude,
Body acceleration smallest value FFT magnitude,
Body acceleration signal magnitude area magnitude,
Body acceleration energy measure FFT magnitude,
Body acceleration interquartile range FFT magnitude,
Body acceleration signal entropy FFT magnitude,
Body acceleration index of the frequency component with largest magnitude FFT,
Body acceleration weighted average of the frequency components to obtain a mean frequency FFT magnitude,
Body acceleration skewness of the frequency domain signal FFT magnitude,
Body acceleration kurtosis of the frequency domain signal FFT magnitude,
Body acceleration jerk mean FFT magnitude,
Body acceleration jerk standard deviation FFT magnitude,
Body acceleration jerk median absolute deviation FFT magnitude,
Body acceleration jerk largest value FFT magnitude,
Body acceleration jerk smallest value FFT magnitude,
Body acceleration jerk signal magnitude area magnitude,
Body acceleration jerk energy measure FFT magnitude,
Body acceleration jerk interquartile range FFT magnitude,
Body acceleration jerk signal entropy FFT magnitude,
Body acceleration jerk index of the frequency component with largest magnitude FFT,
Body acceleration jerk weighted average of the frequency components to obtain a mean frequency FFT magnitude,
Body acceleration jerk skewness of the frequency domain signal FFT magnitude,
Body acceleration jerk vkurtosis of the frequency domain signal FFT magnitude,
Body gyroscopic mean FFT magnitude,
Body gyroscopic standard deviation FFT magnitude,
Body gyroscopic median absolute deviation FFT magnitude,
Body gyroscopic largest value FFT magnitude,
Body gyroscopic smallest value FFT magnitude,
Body gyroscopic signal magnitude area magnitude,
Body gyroscopic energy measure FFT magnitude,
Body gyroscopic interquartile range FFT magnitude,
Body gyroscopic signal entropy FFT magnitude,
Body gyroscopic index of the frequency component with largest magnitude FFT,
Body gyroscopic weighted average of the frequency components to obtain a mean frequency FFT magnitude,
Body gyroscopic skewness of the frequency domain signal FFT magnitude,
Body gyroscopic vkurtosis of the frequency domain signal FFT magnitude,
Body gyroscopic jerk mean FFT magnitude,
Body gyroscopic jerk standard deviation FFT magnitude,
Body gyroscopic jerk median absolute deviation FFT magnitude,
Body gyroscopic jerk largest value FFT magnitude,
Body gyroscopic jerk smallest value FFT magnitude,
Body gyroscopic vsignal magnitude area magnitude,
Body gyroscopic jerk energy measure FFT magnitude,
Body gyroscopic jerk interquartile range FFT magnitude,
Body gyroscopic jerk signal entropy FFT magnitude,
Body gyroscopic jerk index of the frequency component with largest magnitude FFT,
Body gyroscopic jerk weighted average of the frequency components to obtain a mean frequency FFT magnitude,
Body gyroscopic jerk skewness of the frequency domain signal FFT magnitude,
Body gyroscopic jerk vkurtosis of the frequency domain signal FFT magnitude,
Angle between body acceleration mean time and mean gravity,
Angle between body acceleration jerk mean time and mean gravity,
Angle between body gyroscopic mean time and mean gravity,
Angle between body gyroscopic jerk mean time and mean gravity,
Angle between X direction and mean gravity,
Angle between Y direction and mean gravity,
Angle between Z direction and mean gravity

* subject_test.txt and subject_train.txt
    + description: each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.
    + contents: subject ID
* y_test.txt and y_train.txt
    + description: test and train activity labels.
    + contents: activity label ID

#### Processed data

We will perform the following transformations, detailed explained in the README.md file:

1. merging the datasets X_test (measurements), subject_test (subjects) and y_test (activity labels) into one single file for test dataset
2. merging the datasets X_train (measurements), subject_train (subjects) and y_train (activity labels) into one single file for train dataset
3. merging both datasets above into one single dataset for all the subjects (train and test)
4. changing the activity ID labels to activity names
5. selecting only the mean and standard deviations variables to work with
6. changing the variable names to more meningful names
7. sumarizing the variable mean grouped by activity and subject
8. writing the data into the tidy text file requested


The description of the tidy dataset follows bellow:

* tidy_project.txt
    
    + description: text file with the mean value grouped by activity and subject, of all the variables that represent means and standard deviations from the raw datasets. 
    
    + contents: 
activity name, subject ID,
Mean value of body acceleration mean time on direction X,
Mean value of body acceleration mean time on direction Y,
Mean value of body acceleration mean time on direction Z,
Mean value of body acceleration standard deviation time on direction X,
Mean value of body acceleration standard deviation time on direction Y,
Mean value of body acceleration standard deviation time on direction Z,
Mean value of gravity acceleration mean time on direction X,
Mean value of gravity acceleration mean time on direction Y,
Mean value of gravity acceleration mean time on direction Z,
Mean value of gravity acceleration standard deviation time on direction X,
Mean value of gravity acceleration standard deviation time on direction Y,
Mean value of gravity acceleration standard deviation time on direction Z,
Mean value of body acceleration jerk mean time on direction X,
Mean value of body acceleration jerk mean time on direction Y,
Mean value of body acceleration jerk mean time on direction Z,
Mean value of body acceleration jerk standard deviation time on direction X,
Mean value of body acceleration jerk standard deviation time on direction Y,
Mean value of body acceleration jerk standard deviation time on direction Z,                 
Mean value of body gyroscopic mean time on direction X,
Mean value of body gyroscopic mean time on direction Y,
Mean value of body gyroscopic mean time on direction Z,
Mean value of body gyroscopic standard deviation time on direction X,
Mean value of body gyroscopic standard deviation time on direction Y,
Mean value of body gyroscopic standard deviation time on direction Z,
Mean value of body gyroscopic jerk mean time on direction X,
Mean value of body gyroscopic jerk mean time on direction Y,
Mean value of body gyroscopic jerk mean time on direction Z,
Mean value of body gyroscopic jerk standard deviation time on direction X,
Mean value of body gyroscopic jerk standard deviation time on direction Y,
Mean value of body gyroscopic jerk standard deviation time on direction Z,
Mean value of body acceleration mean time magnitude,
Mean value of body acceleration standard deviation time magnitude,
Mean value of gravity acceleration mean time magnitude,
Mean value of gravity acceleration standard deviation time magnitude,
Mean value of body acceleration jerk mean time magnitude,
Mean value of body acceleration jerk standard deviation time magnitude,
Mean value of body gyroscopic mean time magnitude,
Mean value of body gyroscopic standard deviation time magnitude,
Mean value of body acceleration jerk mean time magnitude,
Mean value of body acceleration jerk standard deviation time magnitude,
Mean value of body acceleration mean FFT on direction X,
Mean value of body acceleration mean FFT on direction Y,
Mean value of body acceleration mean FFT on direction Z,
Mean value of body acceleration standard deviation FFT on direction X,
Mean value of body acceleration standard deviation FFT on direction Y,
Mean value of body acceleration standard deviation FFT on direction Z,
Mean value of body acceleration jerk mean FFT on direction X,
Mean value of body acceleration jerk mean FFT on direction Y,
Mean value of body acceleration jerk mean FFT on direction Z,
Mean value of body acceleration jerk standard deviation FFT on direction X,
Mean value of body acceleration jerk standard deviation FFT on direction Y,
Mean value of body acceleration jerk standard deviation FFT on direction Z,
Mean value of body gyroscopic mean FFT on direction X,
Mean value of body gyroscopic mean FFT on direction Y,
Mean value of body gyroscopic mean FFT on direction Z,
Mean value of body gyroscopic standard deviation FFT on direction X,
Mean value of body gyroscopic standard deviation FFT on direction Y,
Mean value of body gyroscopic standard deviation FFT on direction Z,
Mean value of body acceleration mean FFT magnitude,
Mean value of body acceleration standard deviation FFT magnitude,
Mean value of body acceleration mean FFT magnitude,
Mean value of body acceleration standard deviation FFT magnitude,
Mean value of body gyroscopic mean FFT magnitude,
Mean value of body gyroscopic standard deviation FFT magnitude,
Mean value of body gyroscopic jerk mean FFT magnitude,
Mean value of body gyroscopic jerk standard deviation FFT magnitude



